server:
  port: 8081

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file://D:/Tutorials/application-config

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/